name: flutter_app
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  inject :
    path : ./vendor/inject.dart/package/inject
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  scoped_model: ^1.0.1
  rxdart: ^0.18.0
  http: ^0.12.0+1
  redux_thunk: ^0.2.0
  flutter_redux : ^0.5.2
  dependencies_flutter: ^0.1.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  inject_generator:
    path: ./vendor/inject.dart/package/inject_generator
  font_awesome_flutter: ^8.0.1
flutter:

  uses-material-design: true

  assets:
    - assets/login_logo.png

  fonts:
    - family: WorkSansSemiBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf

    - family: WorkSansBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf

    - family: WorkSansMedium
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf

